services:
  - type: web
    name: revenue-performance-app
    env: python
    plan: free
    region: oregon

    # Build the frontend, then install backend deps
    buildCommand: |
      cd frontend
      npm ci
      npm run build
      cd ..
      mkdir -p backend/static
      # copy React build into backend/static
      cp -R frontend/build/* backend/static/
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      gunicorn -w 2 -k uvicorn.workers.UvicornWorker backend.app:app --bind 0.0.0.0:$PORT

    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: MATERIALITY_PCT
        value: "0.03"
      - key: PERF_OVER_PCT
        value: "0.05"
      - key: PERF_UNDER_PCT
        value: "-0.05"
      # Point frontend at same origin (served by this app)
      - key: REACT_APP_API_BASE
        value: "/api"

    # No disks on free plan; write temp artifacts to /tmp if needed
