services:
  - type: web
    name: revenue-performance-app
    env: python
    plan: free
    region: oregon

    envVars:
      - key: REACT_APP_API_BASE
        value: "/api"
      - key: MATERIALITY_PCT
        value: "0.03"
      - key: PERF_OVER_PCT
        value: "0.05"
      - key: PERF_UNDER_PCT
        value: "-0.05"
      - key: PYTHONUNBUFFERED
        value: "1"

    buildCommand: |
      set -euxo pipefail
      # Frontend
      cd frontend
      if [ -f package-lock.json ]; then npm ci; else npm install; fi
      npm run build
      test -d build

      # Backend
      cd ..
      python -m pip install --upgrade pip
      pip install -r requirements.txt

      mkdir -p backend/static
      cp -R frontend/build/* backend/static/

    startCommand: |
      set -euxo pipefail
      python -c "import backend.app; print('✅ backend.app import OK')"
      exec gunicorn -w 2 -k uvicorn.workers.UvicornWorker backend.app:app --bind 0.0.0.0:$PORT
