import React, { useState, useEffect } from "react";

const Downloads = () => {
  const [outputs, setOutputs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Fetch list of generated output files from backend
  useEffect(() => {
    fetchOutputs();
  }, []);

  const fetchOutputs = async () => {
    try {
      setLoading(true);
      const response = await fetch("/api/download/list");
      if (!response.ok) {
        throw new Error(`HTTP error! Status: ${response.status}`);
      }
      const data = await response.json();
      setOutputs(data.files || []);
      setError(null);
    } catch (err) {
      console.error("Error fetching outputs:", err);
      setError("Failed to load output files. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const downloadFile = (filename) => {
    window.open(`/api/download/file?filename=${encodeURIComponent(filename)}`, "_blank");
  };

  const formatFileSize = (bytes) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };

  const formatDate = (timestamp) => {
    return new Date(timestamp * 1000).toLocaleString();
  };

  const getFileIcon = (filename) => {
    const ext = filename.split('.').pop()?.toLowerCase();
    switch (ext) {
      case 'csv':
        return '📊';
      case 'xlsx':
      case 'xls':
        return '📈';
      case 'json':
        return '📋';
      case 'txt':
        return '📄';
      default:
        return '📁';
    }
  };

  if (loading) {
    return (
      <div style={{ padding: "20px", textAlign: "center" }}>
        <h1>📥 Downloads</h1>
        <div style={{ marginTop: "50px" }}>
          <div style={{ fontSize: "24px", marginBottom: "10px" }}>⏳</div>
          <p>Loading output files...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div style={{ padding: "20px", textAlign: "center" }}>
        <h1>📥 Downloads</h1>
        <div style={{ marginTop: "50px" }}>
          <div style={{ fontSize: "24px", marginBottom: "10px", color: "#dc3545" }}>❌</div>
          <p style={{ color: "#dc3545" }}>{error}</p>
          <button
            onClick={fetchOutputs}
            style={{
              background: "#007bff",
              color: "#fff",
              border: "none",
              padding: "10px 20px",
              borderRadius: "4px",
              cursor: "pointer",
              marginTop: "10px"
            }}
          >
            🔄 Retry
          </button>
        </div>
      </div>
    );
  }

  return (
    <div style={{ padding: "20px" }}>
      <h1>📥 Downloads</h1>
      <p style={{ color: "#666", marginBottom: "20px" }}>
        Download the output files generated by your pipeline runs.
      </p>

      {outputs.length > 0 ? (
        <div>
          <div style={{ 
            background: "#e7f3ff", 
            padding: "15px", 
            borderRadius: "5px", 
            marginBottom: "20px",
            border: "1px solid #b3d9ff"
          }}>
            <h3 style={{ margin: "0 0 10px 0", color: "#0056b3" }}>
              🎉 Pipeline Outputs Available
            </h3>
            <p style={{ margin: 0, color: "#0056b3" }}>
              {outputs.length} file{outputs.length !== 1 ? 's' : ''} ready for download
            </p>
          </div>

          <div style={{ display: "grid", gap: "15px" }}>
            {outputs.map((file, idx) => (
              <div key={idx} style={{ 
                display: "flex", 
                justifyContent: "space-between", 
                alignItems: "center",
                padding: "20px",
                background: "white",
                border: "1px solid #ddd",
                borderRadius: "8px",
                boxShadow: "0 2px 4px rgba(0,0,0,0.1)"
              }}>
                <div style={{ display: "flex", alignItems: "center", gap: "15px" }}>
                  <div style={{ fontSize: "32px" }}>
                    {getFileIcon(file.name)}
                  </div>
                  <div>
                    <h3 style={{ margin: "0 0 5px 0", fontSize: "18px" }}>
                      {file.name}
                    </h3>
                    <div style={{ fontSize: "0.9em", color: "#666" }}>
                      <span style={{ marginRight: "15px" }}>
                        📏 Size: {formatFileSize(file.size_bytes)}
                      </span>
                      <span>
                        🕒 Modified: {formatDate(file.modified_at)}
                      </span>
                    </div>
                  </div>
                </div>
                <button
                  style={{
                    background: "#28a745",
                    color: "#fff",
                    border: "none",
                    padding: "12px 24px",
                    cursor: "pointer",
                    borderRadius: "6px",
                    fontWeight: "bold",
                    fontSize: "16px",
                    transition: "background-color 0.2s"
                  }}
                  onMouseOver={(e) => e.target.style.background = "#218838"}
                  onMouseOut={(e) => e.target.style.background = "#28a745"}
                  onClick={() => downloadFile(file.relpath)}
                >
                  📥 Download
                </button>
              </div>
            ))}
          </div>
        </div>
      ) : (
        <div style={{ 
          background: "#f8f9fa", 
          padding: "40px", 
          borderRadius: "8px",
          textAlign: "center",
          border: "2px dashed #ddd"
        }}>
          <div style={{ fontSize: "48px", marginBottom: "20px" }}>📁</div>
          <h3 style={{ margin: "0 0 15px 0", color: "#666" }}>
            No Output Files Yet
          </h3>
          <p style={{ margin: "0 0 20px 0", color: "#666" }}>
            Pipeline outputs will appear here after you upload a file and run the pipeline.
          </p>
          <div style={{ 
            background: "#fff", 
            padding: "15px", 
            borderRadius: "5px",
            display: "inline-block",
            border: "1px solid #ddd"
          }}>
            <p style={{ margin: "0", fontSize: "14px", color: "#666" }}>
              <strong>Next steps:</strong><br/>
              1. Go to <strong>Upload Data</strong> page<br/>
              2. Upload your CSV or Excel file<br/>
              3. Click <strong>Upload & Run Pipeline</strong><br/>
              4. Return here to download results
            </p>
          </div>
        </div>
      )}
    </div>
  );
};

export default Downloads;
